# Generated by Django 2.0.5 on 2018-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='update_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
