# Generated by Django 2.0.5 on 2018-05-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180503_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
