# Generated by Django 2.0.5 on 2018-05-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180503_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
