# Generated by Django 2.0.5 on 2018-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180503_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='images',
            field=models.ImageField(blank=True, height_field='url_height', null=True, upload_to='art_img', width_field='url_width'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='url_height',
            field=models.PositiveIntegerField(default=225),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='url_width',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
