# Generated by Django 2.0.5 on 2018-05-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180503_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
