# Generated by Django 2.0.5 on 2018-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogarticle_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='show_img',
            field=models.BooleanField(default=False),
        ),
    ]
