# Generated by Django 2.0.5 on 2018-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogarticle_show_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
